services:

  db:
    image: postgres
    ports: 
     - "5432:5432"
    restart: always 
    environment:
      POSTGRES_USER: common_database
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres