services:

  db:
    image: postgres
    container_name: inji_usecase
    ports: 
     - "5432:5432"
    restart: always 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  pgdata: